# Generated by Django 5.0.1 on 2024-01-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateQuizApp', '0002_quizlibary_delete_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quizmaster', models.CharField(max_length=12)),
                ('Question', models.CharField(max_length=200)),
                ('Answer1', models.CharField(max_length=50)),
                ('Answer2', models.CharField(max_length=50)),
                ('Answer3', models.CharField(max_length=50)),
                ('Answer4', models.CharField(max_length=50)),
                ('RightAnswerInt', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='quizlibary',
            name='Answer1',
        ),
        migrations.RemoveField(
            model_name='quizlibary',
            name='Answer2',
        ),
        migrations.RemoveField(
            model_name='quizlibary',
            name='Answer3',
        ),
        migrations.RemoveField(
            model_name='quizlibary',
            name='Answer4',
        ),
        migrations.RemoveField(
            model_name='quizlibary',
            name='Question',
        ),
        migrations.RemoveField(
            model_name='quizlibary',
            name='Quizmaster',
        ),
        migrations.RemoveField(
            model_name='quizlibary',
            name='RightAnswerInt',
        ),
        migrations.AddField(
            model_name='quizlibary',
            name='NumberOfQuestions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizlibary',
            name='Questions',
            field=models.ManyToManyField(blank=True, to='CreateQuizApp.question'),
        ),
    ]
