# Generated by Django 5.0.1 on 2024-01-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateQuizApp', '0003_question_remove_quizlibary_answer1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='RightAnswerInt',
        ),
        migrations.AlterField(
            model_name='question',
            name='Answer1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='Answer2',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='Answer3',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='Answer4',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='Quizmaster',
            field=models.CharField(max_length=32),
        ),
    ]
