# Generated by Django 5.0.1 on 2024-01-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateQuizApp', '0004_remove_question_rightanswerint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizlibary',
            name='NumberOfQuestions',
        ),
        migrations.AddField(
            model_name='question',
            name='CorrectAnswer',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
