# Generated by Django 5.0.1 on 2024-01-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateQuizApp', '0005_remove_quizlibary_numberofquestions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizlibary',
            name='Quizmaster',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
