# Generated by Django 5.0.1 on 2024-01-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateQuizApp', '0006_quizlibary_quizmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizlibary',
            name='QuizID',
        ),
    ]
