# Generated by Django 5.0.1 on 2024-01-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateQuizApp', '0007_remove_quizlibary_quizid'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='CorrectAnswerIndex',
            field=models.IntegerField(default=0),
        ),
    ]
