# Generated by Django 5.0.1 on 2024-01-15 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateQuizApp', '0008_question_correctanswerindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='CorrectAnswer',
        ),
        migrations.AlterField(
            model_name='question',
            name='CorrectAnswerIndex',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
